const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  rules: [
    //
    // {
    //   // // Targets only CSS files generated by vanilla-extract
    //   test: /\.vanilla\.css$/i,
    //   use: [
    //     MiniCssExtractPlugin.loader,
    //     {
    //       loader: require.resolve('css-loader'),
    //       options: {
    //         url: false
    //       }
    //     }
    //   ]
    // },
    {
      test: /\.(js|ts|tsx)$/,
      exclude: /node_modules/,
      use: [
        {
          loader: require.resolve("babel-loader"),
          options: {
            plugins: [require.resolve("@vanilla-extract/babel-plugin")],
          },
        }
      ]
    },
    {
      test: /\.(ts|tsx)?$/,
      loader: require.resolve("ts-loader"),
      exclude: /node_modules/
    },
    {
      test: /\.(png|svg|jpg|jpeg|gif)$/i,
      type: 'asset/resource',
    },
  ]
}